### ISSUE TITLE
Request for Transfer of Ownership for `mmdb-writer` on PyPI

### ISSUE THREAD

**Issue by vimt** [cercide/mmdb#1]
Hello cercide,

I hope you are doing well. I am writing to you regarding the ‘mmdb-writer’ project currently listed on PyPI at https://pypi.org/project/mmdb-writer/. I am the original author of [this project](https://github.com/vimt/MaxMind-DB-Writer-python), and I noticed that it has been uploaded to PyPI.

While I appreciate your initiative in sharing this package with the broader community, I would like to request the transfer of the ownership of this PyPI project to my account. My PyPI account email is me@vimt.me.

Please let me know if you need any further information or verification from my side to facilitate this transfer. Ensing the project is kept up-to-date and managed directly would be beneficial for its continued development and use.

Thank you for your understanding and support.

**Comment by cercide** [comment]
Hey there,

Thanks for reaching out. Please send me your pypi username.

**Comment by vimt** [comment]
Thank you for your prompt response! Here's the link to my PyPI profile: https://pypi.org/user/VimT/.

Please let me know if there is anything else you need from me to proceed with the transfer. I appreciate your help with this!

Best regards

**Comment by cercide** [comment]
You should have received an invitation by now.

**Comment by vimt** [comment]
I have successfully received the invitation and am now listed as the owner of the mmdb-writer package on PyPI. Thank you very much for your help.

Best regards.
